{% set name = "alive-progress" %}
{% set version = "3.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ede29d046ff454fe56b941f686f89dd9389430c4a5b7658e445cb0b80e0e4deb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }},<4
    - about-time ==4.2.1
    - grapheme ==0.6.0

test:
  imports:
    - alive_progress
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rsalmei/alive-progress
  summary: A new kind of Progress Bar, with real-time throughput, ETA, and very cool animations!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Brainor
    - marcelotrevisani
