{% set name = "alive-progress" %}
{% set version = "3.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 42e399a66c8150dc507602dff7b7953f105ef11faf97ddaa6d27b1cbf45c4c98

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }},<4
    - about-time ==4.2.1
    - grapheme ==0.6.0

test:
  imports:
    - alive_progress
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/rsalmei/alive-progress
  summary: A new kind of Progress Bar, with real-time throughput, ETA, and very cool animations!
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Brainor
    - marcelotrevisani
